title: StackToHeap
email: manojlds@gmail.com
description: >
  StackToHeap: No Overflow
baseurl: ""
url: "https://stacktoheap.com"
permalink: /blog/:year/:month/:day/:title/

twitter_username: manojlds
github_username:  manojlds

markdown: kramdown
exclude: [Gemfile, Gemfile.lock, deploy.sh, build.sh, vendor]

disqus_short_name: stacktoheap
disqus_show_comment_count: true

google_analytics_tracking_id: UA-35693303-1

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
  - build.sh
  - deploy.sh

jekyll-archives:
  enabled:
  - categories
  - tags
  - year
  layouts:
    tag: 'category'
    category: 'category'
    year: 'archive'
  permalinks:
    year: '/archives/:year/'
    month: '/archives/:year/:month/'
    day: '/archives/:year/:month/:day/'
    tag: '/tags/:name/'
    category: '/categories/:name/'
